# Generated by Django 6.0.7 on 2026-07-11 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('code', models.CharField(max_length=8, unique=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=16)),
                ('slot_type', models.CharField(choices=[('MOTORCYCLE', 'Motorcycle'), ('CAR', 'Car'), ('SUV', 'SUV'), ('VAN', 'Van'), ('TRUCK', 'Truck')], default='CAR', max_length=16)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('MAINTENANCE', 'Under maintenance')], default='AVAILABLE', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='parking.floor')),
            ],
            options={
                'ordering': ['floor__sort_order', 'code'],
                'constraints': [models.UniqueConstraint(fields=('floor', 'code'), name='unique_slot_code_per_floor')],
            },
        ),
    ]
