# Generated by Django 6.0.7 on 2026-07-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='image',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
