# Generated by Django 6.0.7 on 2026-07-14 09:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_floor_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='OccupancySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('total', models.PositiveIntegerField()),
                ('available', models.PositiveIntegerField()),
                ('occupied', models.PositiveIntegerField()),
                ('maintenance', models.PositiveIntegerField()),
                ('paid_revenue_cents', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
    ]
