# Generated by Django 6.0.7 on 2026-07-13.

from django.db import migrations, models


def remove_duplicate_receipts(apps, schema_editor):
    """Keep the earliest canonical receipt before enforcing uniqueness."""
    BillingRecord = apps.get_model("payments", "BillingRecord")
    duplicate_payment_ids = (
        BillingRecord.objects.exclude(payment_id=None)
        .values("payment_id")
        .annotate(total=models.Count("id"))
        .filter(total__gt=1)
        .values_list("payment_id", flat=True)
    )
    for payment_id in duplicate_payment_ids:
        canonical = (
            BillingRecord.objects.filter(payment_id=payment_id)
            .order_by("issued_at", "pk")
            .first()
        )
        BillingRecord.objects.filter(payment_id=payment_id).exclude(
            pk=canonical.pk
        ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="confirmation_notified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="failure_notified_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(
            remove_duplicate_receipts,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="billingrecord",
            constraint=models.UniqueConstraint(
                fields=("payment",),
                name="unique_billing_record_per_payment",
            ),
        ),
    ]
