# Generated by Django 6.0.7 on 2026-07-13.

import uuid

import django.db.models.deletion
from django.db import migrations, models


def populate_checkout_idempotency_keys(apps, schema_editor):
    """Assign a distinct stable key to every payment that predates this field."""

    Payment = apps.get_model("payments", "Payment")
    for payment in Payment.objects.filter(
        checkout_idempotency_key__isnull=True
    ).iterator():
        payment.checkout_idempotency_key = uuid.uuid4()
        payment.save(update_fields=["checkout_idempotency_key"])


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_payment_notification_guards"),
    ]

    operations = [
        # Add the UUID as nullable first so existing databases can receive one
        # unique generated value per row before the uniqueness constraint lands.
        migrations.AddField(
            model_name="payment",
            name="checkout_idempotency_key",
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.RunPython(
            populate_checkout_idempotency_keys,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="payment",
            name="checkout_idempotency_key",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.CreateModel(
            name="PayMongoWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.CharField(max_length=128, unique=True)),
                ("event_type", models.CharField(max_length=64)),
                ("livemode", models.BooleanField()),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("PROCESSED", "Processed"),
                            ("IGNORED", "Ignored"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="IGNORED",
                        max_length=16,
                    ),
                ),
                ("detail", models.CharField(blank=True, max_length=255)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="webhook_events",
                        to="payments.payment",
                    ),
                ),
            ],
            options={"ordering": ["-received_at"]},
        ),
    ]
