# Generated by Django 6.0.7 on 2026-07-13.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.CheckConstraint(
                condition=models.Q(end_at__gt=models.F("start_at")),
                name="reservation_end_after_start",
            ),
        ),
    ]
