# Generated by Django 6.0.7 on 2026-07-14 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_reservation_window_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
